"""Create human-readable Vega/Vega-Lite specifications from published data."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]/'dist';S=R/'specs'
VL='https://vega.github.io/schema/vega-lite/v6.json';V='https://vega.github.io/schema/vega/v6.json'
B='#176b91';O='#c45222';INK='#132a40';GRAY='#c9d5df'
def out(name,s): (S/name).write_text(json.dumps(s,indent=2)+'\n')
def base(url,h=300):return {'$schema':VL,'height':h,'data':{'url':'data/'+url}}
def q(f,title=None,**kw):return dict(field=f,type='quantitative',**({'title':title} if title else {}),**kw)
def n(f,**kw):return dict(field=f,type='nominal',**kw)
def tip(f,fmt=None,title=None):return dict(field=f,**({'type':'quantitative','format':fmt} if fmt else {}),**({'title':title} if title else {}))
# Waterfall decomposition uses national totals, not cohort transitions.
w=base('national-total.json',300);w['data']={'values':[{'Step':'2022 peak','Start':0,'End':372885,'Kind':'Total','Label':'372,885','Order':0},{'Step':'2023 change','Start':337245,'End':372885,'Kind':'Decrease','Label':'−35,640','Order':1},{'Step':'2024 change','Start':309080,'End':337245,'Kind':'Decrease','Label':'−28,165','Order':2},{'Step':'2025 change','Start':282430,'End':309080,'Kind':'Decrease','Label':'−26,650','Order':3},{'Step':'2025 total','Start':0,'End':282430,'Kind':'Total','Label':'282,430','Order':4}]}
w['description']='Waterfall: changes in national active contracts from the 2022 peak to 2025. All bars use a common zero-based vertical scale.'
w['encoding']={'x':n('Step',sort={'field':'Order'},axis={'title':None,'labelAngle':0,'labelLimit':140}),'y':q('End',axis={'title':'Active contracts','format':'~s'},scale={'domain':[0,420000]}),'y2':{'field':'Start'},'tooltip':[tip('Step'),tip('Label',title='Contracts')]}
w['layer']=[{'mark':{'type':'bar','size':70},'encoding':{'color':n('Kind',scale={'domain':['Total','Decrease'],'range':[B,O]},legend=None)}},{'mark':{'type':'text','dy':-10,'fontWeight':600},'encoding':{'text':{'field':'Label'},'y2':None}}]
out('02-waterfall.json',w)
# Geographic maps use the same geographic reference, but distinct encodings.
focus={'name':'focusState','value':'All'}
projection={'type':'conicEqualArea','parallels':[-18,-36],'rotate':[-134,0,0],'center':[0,-27]}
lookup={'lookup':'properties.State','from':{'data':{'url':'data/states.json'},'key':'State','fields':['Contracts','Population','Rate','Short','Change']}}
for kind,num in [('choropleth','03'),('symbols','04')]:
 s={'$schema':VL,'height':365,'params':[focus],'projection':projection,'layer':[],'description':f'{kind} map of Australian training contracts at 31 December 2025. ABS generalised boundaries, Albers equal-area projection.'}
 geolayer={'data':{'url':'data/abs-states-simplified.geojson','format':{'type':'json','property':'features'}},'transform':[lookup],'mark':{'type':'geoshape','stroke':'white','strokeWidth':1.3},'encoding':{}}
 if kind=='choropleth':geolayer['encoding']={'color':q('Rate',scale={'domain':[7,13],'range':['#e5f1f6','#07516f']},legend={'title':'Contracts per 1,000 residents','orient':'bottom','format':'.0f','gradientLength':230}),'stroke':{'condition':{'test':"datum.properties.State === focusState",'value':O},'value':'white'},'strokeWidth':{'condition':{'test':"datum.properties.State === focusState",'value':3},'value':1.3},'tooltip':[tip('properties.State',title='State / territory'),tip('Contracts',','),tip('Population',','),tip('Rate','.1f','Contracts per 1,000 residents')]}
 else:geolayer['mark']['fill']='#eaf0f4';geolayer['mark']['stroke']='#bccbd5'
 s['layer'].append(geolayer)
 if kind=='symbols':s['layer'].append({'data':{'url':'data/states.json'},'mark':{'type':'circle','opacity':.8,'stroke':'white','strokeWidth':1.5},'encoding':{'longitude':q('Longitude'),'latitude':q('Latitude'),'size':q('Contracts',scale={'domain':[0,85000],'range':[0,2600]},legend={'title':'Active contracts','orient':'bottom','values':[5000,40000,80000],'format':'~s','symbolType':'circle'}),'color':{'condition':{'test':'datum.State === focusState','value':O},'value':B},'tooltip':[tip('State'),tip('Contracts',','),tip('Rate','.1f','Per 1,000 residents')]}})
 # ACT gets a leader so the tiny geographic polygon does not disappear.
 s['layer'].append({'data':{'url':'data/states.json'},'transform':[{'filter':"datum.Short !== 'ACT'"}],'mark':{'type':'text','fontSize':13,'fontWeight':700,'stroke':'white','strokeWidth':.2,'dy':-2},'encoding':{'longitude':q('Longitude'),'latitude':q('Latitude'),'text':{'field':'Short'},'color':{'value':INK} if kind=='symbols' else {'condition':{'test':'datum.Rate >= 10.4','value':'#ffffff'},'value':INK}}})
 s['layer'].append({'data':{'values':[{'Longitude':149.1,'Latitude':-35.4,'Longitude2':154,'Latitude2':-36.5}]},'mark':{'type':'rule','color':INK,'strokeWidth':1},'encoding':{'longitude':q('Longitude'),'latitude':q('Latitude'),'longitude2':{'field':'Longitude2'},'latitude2':{'field':'Latitude2'}}})
 s['layer'].append({'data':{'values':[{'Longitude':154,'Latitude':-36.5,'Label':'ACT'}]},'mark':{'type':'text','align':'left','dx':3,'fontSize':12,'fontWeight':700,'color':INK},'encoding':{'longitude':q('Longitude'),'latitude':q('Latitude'),'text':{'field':'Label'}}})
 out(f'{num}-{kind}.json',s)
# Geographic cartogram geometry and specification have a dedicated audited builder.
import runpy
runpy.run_path(str(Path(__file__).with_name('build_cartogram.py')))
# Treemap: Vega's hierarchy/treemap transforms, preserving published leaf counts.
s={'$schema':V,'description':'Treemap of active contracts in the seven trade occupation groups, December 2025. Rectangle areas encode published counts.','width':900,'height':360,'padding':0,'autosize':'fit',
'data':[{'name':'tree','url':'data/trade-tree.json','transform':[{'type':'stratify','key':'id','parentKey':'parent'},{'type':'treemap','field':'Contracts','sort':{'field':'value','order':'descending'},'method':'squarify','ratio':1.4,'size':[{'signal':'width'},{'signal':'height'}],'paddingInner':4,'round':True}]},{'name':'leaves','source':'tree','transform':[{'type':'filter','expr':'!datum.children'}]}],
'scales':[{'name':'color','type':'ordinal','domain':{'data':'leaves','field':'Occupation'},'range':['#176b91','#24506d','#3981a2','#516f86','#698c9e','#759eb0','#8bb4c4']}], 'marks':[]}
s['marks'].append({'type':'rect','from':{'data':'leaves'},'encode':{'update':{'x':{'field':'x0'},'y':{'field':'y0'},'x2':{'field':'x1'},'y2':{'field':'y1'},'fill':{'scale':'color','field':'Occupation'},'tooltip':{'signal':"{'Occupation':datum.FullName,'Active contracts':format(datum.Contracts,','),'Share of shown groups':format(datum.Contracts / 208945,'.1%')}"}},'hover':{'fillOpacity':{'value':.85}}}})
s['marks'].append({'type':'text','from':{'data':'leaves'},'encode':{'update':{'x':{'signal':'datum.x0+12'},'y':{'signal':'datum.y0+19'},'text':{'field':'Label'},'fontSize':{'value':15},'lineHeight':{'value':18},'fontWeight':{'value':600},'fill':{'value':'white'},'limit':{'signal':'max(0,datum.x1-datum.x0-22)'},'opacity':{'signal':'datum.x1-datum.x0 > 80 && datum.y1-datum.y0 > 48 ? 1 : 0'}}}})
s['marks'].append({'type':'text','from':{'data':'leaves'},'encode':{'update':{'x':{'signal':'datum.x0+12'},'y':{'signal':'datum.y1-15'},'text':{'signal':"format(datum.Contracts,',')"},'fontSize':{'value':20},'fill':{'value':'white'},'opacity':{'signal':'datum.x1-datum.x0 > 80 && datum.y1-datum.y0 > 80 ? 1 : 0'}}}})
out('06-treemap.json',s)
s=base('occupations.json',480);s['params']=[{'name':'occupationGroup','value':'All'}];s['transform']=[{'filter':"occupationGroup === 'All' || datum.Group === occupationGroup"}];s['description']='Heatmap: percentage change in active contracts relative to each occupation group’s own 2021 baseline. Counts are independently rounded.'
s['encoding']={'x':{'field':'Year','type':'ordinal','axis':{'title':None,'labelAngle':0,'orient':'top'}},'y':n('Occupation',sort=[i['Occupation'] for i in json.loads((R/'data/occupations.json').read_text()) if i['Year']==2021],axis={'title':None,'labelLimit':280,'labelFontSize':13}),'tooltip':[tip('FullName',title='Occupation'),tip('Year'),tip('Contracts',','),tip('ChangeFrom2021','.1f','Change from 2021 (%)')]}
s['layer']=[{'mark':{'type':'rect','stroke':'white','strokeWidth':3},'encoding':{'color':q('ChangeFrom2021',scale={'domain':[-85,0,50],'range':['#a94422','#f2f4f5','#176b91']},legend={'orient':'bottom','title':'Change from 2021 (%)','gradientLength':260})}},{'mark':{'type':'text','fontSize':13},'encoding':{'text':{'field':'ChangeFrom2021','format':'+.0f'},'color':{'condition':{'test':'datum.ChangeFrom2021 < -40 || datum.ChangeFrom2021 > 15','value':'white'},'value':INK}}}]
out('07-heatmap.json',s)
s=base('occupation-ranks.json',440);s['params']=[{'name':'rankFocus','value':'Aged & disabled carers'}];s['description']='Bump chart: annual ranks within the ten non-trade occupations with the most active contracts in 2025. These are not ranks among all occupations.'
s['encoding']={'x':q('Year',axis={'title':None,'format':'d','tickMinStep':1,'grid':False},scale={'zero':False,'domain':[2021,2025.6]}),'y':q('Rank',axis={'title':'Rank within the ten shown','values':list(range(1,11))},scale={'domain':[10.5,.5],'zero':False}),'detail':n('Occupation'),'color':{'condition':{'test':'datum.Occupation === rankFocus','value':O},'value':'#b7c7d2'},'tooltip':[tip('Occupation'),tip('Year'),tip('Rank'),tip('Contracts',',')]}
s['layer']=[{'mark':{'type':'line','strokeWidth':2.5,'point':{'filled':True,'size':50}}},{'transform':[{'filter':'datum.Year === 2025'}],'mark':{'type':'text','align':'left','dx':10,'fontSize':12},'encoding':{'text':{'field':'Rank'},'color':{'value':INK}}},{'transform':[{'filter':'datum.Occupation === rankFocus'}],'mark':{'type':'line','strokeWidth':4,'point':{'filled':True,'size':90}}}]
out('08-bump.json',s)
s=base('cohorts.json',235);s['params']=[{'name':'cohortFocus','value':'Females'}];s['description']='Waffle chart: share of active contracts associated with a selected cohort in 2025. One square is one percentage point; share is rounded to the nearest whole square. Cohorts overlap.'
s['transform']=[{'filter':'datum.Year === 2025 && datum.Cohort === cohortFocus'},{'calculate':'sequence(0,100)','as':'cells'},{'flatten':['cells']},{'calculate':'datum.cells % 20','as':'col'},{'calculate':'floor(datum.cells/20)','as':'row'},{'calculate':"datum.cells < round(datum.Share) ? 'Selected cohort' : 'All other contracts'",'as':'Membership'}]
s['mark']={'type':'rect','cornerRadius':1,'stroke':'white','strokeWidth':3};s['encoding']={'x':{'field':'col','type':'ordinal','axis':None},'y':{'field':'row','type':'ordinal','axis':None},'color':n('Membership',scale={'domain':['Selected cohort','All other contracts'],'range':[O,'#e3eaf0']},legend=None),'tooltip':[tip('Cohort'),tip('Contracts',','),tip('Share','.1f','Share of all contracts (%)')]}
out('09-waffle.json',s)
s=base('cohort-change.json',335);s['transform']=[{'calculate':'datum.After / datum.Before * 100','as':'Index'},{'calculate':"format(datum.Change, '.1f') + '%'",'as':'Label'}];s['description']='Dumbbell comparison: each cohort’s active contracts in 2025 as an index with its 2024 count set to 100. Groups overlap.'
s['encoding']={'y':n('Cohort',sort=['Females','Language other than English','Regional & remote','Indigenous Australians','People with disability'],axis={'title':None,'labelLimit':230,'labelFontSize':13}),'tooltip':[tip('Cohort'),tip('Before',',','2024 contracts'),tip('After',',','2025 contracts'),tip('Change','.1f','Change (%)')]}
s['layer']=[{'mark':{'type':'rule','strokeWidth':3,'color':GRAY},'encoding':{'x':q('Index',axis={'title':'2024 = 100','values':[85,90,95,100]},scale={'domain':[82,102],'zero':False}),'x2':{'datum':100}}},{'mark':{'type':'point','filled':True,'size':80,'color':GRAY},'encoding':{'x':{'datum':100}}},{'mark':{'type':'point','filled':True,'size':110,'color':O},'encoding':{'x':q('Index')}},{'mark':{'type':'text','align':'right','dx':-10,'fontSize':13,'color':O,'fontWeight':600},'encoding':{'x':q('Index'),'text':{'field':'Label'}}}]
out('10-cohort-change.json',s)
s=base('employment-pattern.json',335);s['description']='Mosaic chart: column width represents each trade group’s share of trade-classified active contracts; segment height represents the published full-time/part-time percentage within that group. Percentages rounded by NCVER.'
s['transform']=[{'calculate':"datum.Group === 'Trade' ? 0 : 208950 / (208950 + 73475)",'as':'x0'},{'calculate':"datum.Group === 'Trade' ? 208950 / (208950 + 73475) : 1",'as':'x1'},{'calculate':"datum.Arrangement === 'Full-time' ? 0 : (datum.Group === 'Trade' ? .92 : .557)",'as':'y0'},{'calculate':"datum.Arrangement === 'Full-time' ? datum.Percent/100 : 1",'as':'y1'},{'calculate':'(datum.x0+datum.x1)/2','as':'xm'},{'calculate':'(datum.y0+datum.y1)/2','as':'ym'},{'calculate':"datum.Arrangement + ' ' + format(datum.Percent, '.1f') + '%'",'as':'Label'}]
s['encoding']={'tooltip':[tip('Group'),tip('Arrangement'),tip('Percent','.1f','Within-group share (%)'),tip('Contracts',',','All contracts in group')]}
s['layer']=[{'mark':{'type':'rect','stroke':'white','strokeWidth':4},'encoding':{'x':q('x0',scale={'domain':[0,1]},axis=None),'x2':{'field':'x1'},'y':q('y1',scale={'domain':[0,1]},axis=None),'y2':{'field':'y0'},'color':n('Arrangement',scale={'domain':['Full-time','Part-time'],'range':[B,O]},legend={'title':None,'symbolType':'square'})}},{'mark':{'type':'text','fontSize':14,'fontWeight':600,'color':'white'},'encoding':{'x':q('xm'),'y':q('ym'),'text':{'field':'Label'}}}]
out('11-mosaic.json',s)
s=base('annual-activity.json',300);s['description']='Grouped bars compare four separate annual activity counts in 2025. They are not flows through one cohort and cannot be used to calculate a completion probability.'
s['mark']={'type':'bar','cornerRadiusEnd':2};s['encoding']={'y':n('Activity',sort=['Commencements','Recommencements','Completions','Cancellations / withdrawals'],axis={'title':None,'labelLimit':230}),'yOffset':n('Group',sort=['Trade','Non-trade']),'x':q('Contracts',axis={'title':'Contracts recorded during 2025','format':'~s'}),'color':n('Group',scale={'domain':['Trade','Non-trade'],'range':[B,O]},legend={'title':None,'symbolType':'square'}),'tooltip':[tip('Activity'),tip('Group'),tip('Contracts',',')]}
out('12-activity.json',s)
print('Generated eleven specifications; opening line chart retained')
